In [1]:
import pandas as pd

In [2]:
df_global_oil_inventories = pd.read_excel(
    'data/STEO_m.xlsx',
    sheet_name='3atab',
    skiprows=40,
    nrows=2
)

In [3]:
df_global_oil_inventories.head()

,pasc_oecd_t3,OECD total,2647.60185,2619.752228,2605.418099,2656.759189,2668.669406,2656.627603,2713.865088,2718.00758,...,2563.389331,2611.443493,2661.725968,2688.140895,2725.129904,2759.775935,2791.183734,2834.895199,2882.416549,2905.250112
0,pasc_us,United States,1190.10285,1165.614228,1154.238099,1153.830189,1172.156406,1180.409603,1215.318088,1212.67158,...,1235.429000,1256.020000,1275.440000,1280.970000,1293.308000,1298.495000,1303.147000,1300.101000,1310.539000,1303.645000
1,pasc_ooecd_t3,Other OECD,1457.49900,1454.138000,1451.180000,1502.929000,1496.513000,1476.218000,1498.547000,1505.33600,...,1327.960331,1355.423493,1386.285968,1407.170895,1431.821903,1461.280935,1488.036734,1534.794199,1571.877549,1601.605112

In [4]:
df_global_oil_inventories = df_global_oil_inventories.transpose().reset_index()

In [5]:
#VS code only displays so much but it did transpose properly
df_global_oil_inventories.head()

          index              0              1
0  pasc_oecd_t3        pasc_us  pasc_ooecd_t3
1    OECD total  United States     Other OECD
2    2647.60185     1190.10285       1457.499
3   2619.752228    1165.614228       1454.138
4   2605.418099    1154.238099        1451.18

In [6]:
df_global_oil_inventories.columns = df_global_oil_inventories.iloc[1]
df_global_oil_inventories = df_global_oil_inventories.iloc[2:].reset_index(drop=True)

In [7]:
df_global_oil_inventories.columns.name = None

In [8]:
#Add date col
df_global_oil_inventories["Date"] = pd.date_range(
    start="2022-01-01",
    periods=len(df_global_oil_inventories),
    freq="MS"
)

In [9]:
#Move date col to the start
col = ["Date"] + [col for col in df_global_oil_inventories if col != "Date"]
df_global_oil_inventories = df_global_oil_inventories[col]

In [10]:
df_global_oil_inventories = df_global_oil_inventories[df_global_oil_inventories['Date'] <= '2026-09-30']

In [11]:
df_global_oil_inventories.head()

        Date   OECD total United States Other OECD
0 2022-01-01   2647.60185    1190.10285   1457.499
1 2022-02-01  2619.752228   1165.614228   1454.138
2 2022-03-01  2605.418099   1154.238099    1451.18
3 2022-04-01  2656.759189   1153.830189   1502.929
4 2022-05-01  2668.669406   1172.156406   1496.513

In [12]:
df_global_oil_inventories.describe()

                             Date
count                          57
mean   2024-05-01 09:41:03.157894
min           2022-01-01 00:00:00
25%           2023-03-01 00:00:00
50%           2024-05-01 00:00:00
75%           2025-07-01 00:00:00
max           2026-09-01 00:00:00

In [13]:
df_global_oil_inventories.to_csv("data/df_global_oil_inventories_clean.csv", index=False)