In [ ]:
import pandas as pd

In [ ]:
#We only care about the 3 page as of right now, consumption will be considered later
df_global_oil_withdraws = pd.read_excel(
    'data/STEO_m.xlsx',
    sheet_name='3atab',
    skiprows=34,
    nrows=4
)

In [ ]:
df_global_oil_withdraws.head()

,t3_stchange_world,World total,-0.961946,1.094635,-0.646688,-1.355114,-0.048192,1.248508,-0.648759,-0.629257,...,-4.977667,-4.92565,-5.143681,-3.694059,-4.69932,-4.965647,-4.864818,-6.569978,-6.222054,-4.677787
0,t3_stchange_us,United States,0.447567,1.211915,0.780230,0.620097,0.207445,0.717727,-0.309370,0.825662,...,-0.290645,-0.686367,-0.626452,-0.184333,-0.952839,-0.722161,-0.728400,-0.456581,-0.921267,-0.332452
1,t3_stchange_ooecd,Other OECD,-0.416742,0.120036,0.095419,-1.724967,0.206968,0.676500,-0.720290,-0.219000,...,-1.082980,-0.915439,-0.995564,-0.696164,-0.795194,-0.950291,-0.891860,-1.508305,-1.236112,-0.958954
2,t3_stchange_noecd,Other inventory draws and balance,-0.992771,-0.237315,-1.522338,-0.250244,-0.462605,-0.145719,0.380902,-1.235919,...,-3.604042,-3.323844,-3.521666,-2.813562,-2.951287,-3.293194,-3.244558,-4.605092,-4.064675,-3.386382

In [ ]:
df_global_oil_withdraws = df_global_oil_withdraws.transpose().reset_index()

df_global_oil_withdraws.columns = [
    "World Total",
    "USA",
    "OECD",
    "Other Inventory draws and balance"
]

df_global_oil_withdraws = df_global_oil_withdraws.iloc[2:].reset_index(drop=True)

In [ ]:
#Add dates, MS = Month Start
df_global_oil_withdraws["Date"] = pd.date_range(
    start="2022-01-01",
    periods=len(df_global_oil_withdraws),
    freq="MS"
)

In [ ]:
#Move date to the start to reflect original excel sheet
col = ["Date"] + [col for col in df_global_oil_withdraws.columns if col != "Date"]
df_global_oil_withdraws = df_global_oil_withdraws[col]

In [ ]:
df_global_oil_withdraws = df_global_oil_withdraws[df_global_oil_withdraws['Date'] <= '2026-09-30']

In [ ]:
df_global_oil_withdraws.head()

        Date World Total       USA      OECD Other Inventory draws and balance
0 2022-01-01   -0.961946  0.447567 -0.416742                         -0.992771
1 2022-02-01    1.094635  1.211915  0.120036                         -0.237315
2 2022-03-01   -0.646688   0.78023  0.095419                         -1.522338
3 2022-04-01   -1.355114  0.620097 -1.724967                         -0.250244
4 2022-05-01   -0.048192  0.207445  0.206968                         -0.462605

In [ ]:
df_global_oil_withdraws.isnull().sum()

Date                                 0
World Total                          0
USA                                  0
OECD                                 0
Other Inventory draws and balance    0
dtype: int64

In [ ]:
df_global_oil_withdraws.describe()

                      Date
count                   72
mean   2024-12-15 15:20:00
min    2022-01-01 00:00:00
25%    2023-06-23 12:00:00
50%    2024-12-16 12:00:00
75%    2026-06-08 12:00:00
max    2027-12-01 00:00:00

In [ ]:
df_global_oil_withdraws.to_csv("data/df_global_oil_withdraws_clean.csv", index=False)