In [25]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [26]:
#Folder for graphs/fiugures
Path("figures").mkdir(parents=True, exist_ok=True)

In [27]:
path = "data/df_global_oil_"

df_inventories = pd.read_csv(path + "inventories_clean.csv")
df_withdraws = pd.read_csv(path + "withdraws_clean.csv")

In [28]:
df_inventories.head()

    OECD total  United States  Other OECD
0  2647.601850    1190.102850    1457.499
1  2619.752228    1165.614228    1454.138
2  2605.418099    1154.238099    1451.180
3  2656.759189    1153.830189    1502.929
4  2668.669406    1172.156406    1496.513

In [29]:
df_withdraws.head()

   World Total       USA      OECD  Other Inventory draws and balance
0    -0.961946  0.447567 -0.416742                          -0.992771
1     1.094635  1.211915  0.120036                          -0.237315
2    -0.646688  0.780230  0.095419                          -1.522338
3    -1.355114  0.620097 -1.724967                          -0.250244
4    -0.048192  0.207445  0.206968                          -0.462605